### ISSUE TITLE
Cannot read property '0' of undefined error

### ISSUE THREAD

**Issue by gwpl** [Leeiio/tumblr-downloader#5]
```
/usr/lib/node_modules/tumblr-downloader/tumblr.js:115
                    images.push(element['photo-url'][0]._);
                                                    ^

TypeError: Cannot read property '0' of undefined
    at Object.<anonymous> (/usr/lib/node_modules/tumblr-downloader/tumblr.js:115:53)
    at Array.forEach (<anonymous>)
    at Object.parsePosts (/usr/lib/node_modules/tumblr-downloader/tumblr.js:108:19)
    at /usr/lib/node_modules/tumblr-downloader/tumblr.js:31:9
    at fn (/usr/lib/node_modules/tumblr-downloader/node_modules/async/lib/async.js:746:34)
    at /usr/lib/node_modules/tumblr-downloader/node_modules/async/lib/async.js:1213:16
    at /usr/lib/node_modules/tumblr-downloader/node_modules/async/lib/async.js:166:37
    at /usr/lib/node_modules/tumblr-downloader/node_modules/async/lib/async.js:706:43
    at /usr/lib/node_modules/tumblr-downloader/node_modules/async/lib/async.js:167:37
    at Immediate.<anonymous> (/usr/lib/node_modules/tumblr-downloader/node_modules/async/lib/async.js:1206:34)
```

**Comment by Leeiio** [comment]
fixed
